class Configuration:
    def __init__(self):
        self.repertoire_installation_base_defaut = ""
        self.repertoire_installation_base = ""
        self.branch = ""
        self.bdd_address = ""
        self.database = ""
        self.notification_address = ""
        self.database_password = ""
        self.python_application_id = -1
        self.repertoire_telechargement = ""
        self.repertoire_telechargement_temporaire = ""
        self.repertoire_telechargement_texte = ""
        self.repertoire_git_plow_python = ""
        self.rest_address = ""
        self.download_server_address = ""
        self.git_plowshare = ""
        self.repertoire_git_plowshare = ""
        self.git_plow_python = ""
        self.repertoire_git_plow_python = ""
        self.nodejs_version = ""
        self.arm_version = ""
        self.repertoire_git_plow_back_rest = ""
        self.git_plow_back_rest = ""